name: 02 - Workflow Events

on:
    schedule:
        - cron: '*/1 * * * *'

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo ${{ github.event_name }}