name: 04 - Using Actions
on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              run: |
                ls -lR
                cd ../
            - name: Printing Folders
              run: ls -lR
        
