name: 07 - Using Expressions
run-name: "07 - Using Expressions with Debug ${{ inputs.debug == true && 'ON' || 'OFF'}}"

on:
    # push:
    workflow_dispatch:
        inputs:
            debug:
                description: 'Enable Debugging'
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[Debug] Print start-up data"
              if: inputs.debug == true
              run: |
                    echo "Event name: ${{ github.event_name }}"
                    echo "Ref: ${{ github.ref }}"
                    echo "SHA: ${{ github.sha }}"
                    echo "Actor: ${{ github.actor }}"
                    echo "Workflow: ${{ github.workflow }}"
                    echo "Run ID: ${{ github.run_id }}"
                    echo "Run Number: ${{ github.run_number }}"
            - name: "[Debug] Print when triggered from main branch"
              if: github.ref == 'refs/heads/main'
              run: |
                    echo "This job was triggered from the main branch"
            - name: Greetings
              run: |
                    echo "Hello, World!"
            